# Generated by Django 4.1.5 on 2023-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.IntegerField(default=5, verbose_name='Yorum Puanı'),
        ),
    ]
